roles:
  default:
    - packages_default
    - binaries
    - cargo
    - bat
    - cmus
    - fish
    - gnupg
    - interception_tools
    - mutt
    - nvim
    - pass
    - ranger
    - taskwarrior
    - tmux

  gui:
    - packages_gui
    - alacritty
    - flatpak
    - fonts
    - zathura

  dev:
    - packages_dev
    - aws
    - adb
    - asdf
    - docker
    - git
    - nodejs

  gaming:
    - packages_gaming

  gnome:
    - packages_gnome
    - gnome
    - wofi

  hyprland:
    - packages_hyprland
    - hyprland
    - rofi
