#!/bin/sh

libglib2.0-dev
libxinerama-dev
libpango1.0-dev
libstartup-notification0-dev
git clone https://github.com/DaveDavenport/rofi

libxcb-keysyms1-dev
libxcb-icccm4-dev
libyajl-dev
libxcb-dri3-dev
libxkbcommon-dev
libxkbcommon-x11-dev
libxcb-cursor-dev
libxcb-xinerama0-dev
libev-dev
git clone https://www.github.com/Airblader/i3

i3status
i3blocks
xbacklight
libxcb-dpms0-dev
libpam0g-dev
git clone https://github.com/chrjguill/i3lock-color
feh
scrot

https://github.com/jhawthorn/meh.git
libgif-dev
libjpeg-dev

libxcb
libev-dev
libcairo2-dev
libpam0g-dev
libxcb-util-dev
libxcb-dpms0-dev

xautolock
dex
chromium-browser
zathura

(slim)
