#!/bin/bash

MESSAGE=$(cat)
ALIASES="$HOME/.mutt/aliases"

FROM=$(echo "$MESSAGE" \
    | grep '^From: ' \
    | sed s/[\,\'\"]//g)

MAIL=$(echo "${FROM##* }" | sed s/[\<\>]//g)

IFS=' ' read -r -a ARR <<< "$FROM"

if ! grep -m 1 -Fq "$MAIL" "$ALIASES"; then
    if (( ${#ARR[@]} == 2 )); then
        #From: <address>
        #alias address <address>
        echo "alias $MAIL <$MAIL>" >> "$ALIASES"
    elif (( ${#ARR[@]} == 3 )); then
        #From: name <address>
        #alias name <address>
        echo "alias ${ARR[1],,} <$MAIL>" >> "$ALIASES"
    elif (( ${#ARR[@]} > 3 )); then
        #From: forename .. surname <address>
        #alias forename-surname forename .. surname <address>
        unset "ARR[0]"
        unset "ARR[-1]"
        NAME="${ARR[-1]}-${ARR[1]}"
        echo "alias ${NAME,,} ${ARR[*]} <$MAIL>" >> "$ALIASES"
    fi
fi

echo "$MESSAGE"
