#!/bin/sh

MESSAGE=$(cat)

NEWALIAS=$(echo "${MESSAGE}" \
    | grep ^"From: " \
    | sed s/[\,\"\']//g \
    | awk '{$1=""; if (NF == 3) {print "alias" $0;} else if (NF == 2) {print "alias" $0 $0;} else if (NF > 3) {print "alias", tolower($(NF-1))"-"tolower($2) $0;}}')

MAIL=$(echo "${NEWALIAS##* }" | sed s/[\<\>]//g)

if grep -FLq "$MAIL" "$HOME/.mutt/aliases"; then
    echo "$NEWALIAS" >> "$HOME/.mutt/aliases"
fi

echo "${MESSAGE}"
