#!/usr/bin/env bash

oldconf=$1
pid=$(pidof mutt | cut -d' ' -f1)
file="/tmp/mutt_${pid}_pager_index_lines"

if [[ -f $file ]]; then
    conf=$(cat "$file")
    echo "set pager_index_lines=$conf"
    rm "$file"
else
    echo "$oldconf" > "$file"
    echo "set pager_index_lines=0"
fi
