- name: Create cargo folder
  become: true
  ansible.builtin.file:
    path: /opt/cargo
    state: directory
    mode: "0775"
    owner: "{{ user }}"
    group: wheel

- name: Create rustup folder
  become: true
  ansible.builtin.file:
    path: /opt/rustup
    state: directory
    mode: "0775"
    owner: "{{ user }}"
    group: wheel
