- name: Check for OS specific settings
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution | lower }}.yml"
  register: custom_settings

- name: Apply OS specific settings
  ansible.builtin.include_tasks:
    "{{ role_path }}/tasks/{{ ansible_distribution | lower }}.yml"
  when: custom_settings.stat.exists

- name: Install rustup
  ansible.builtin.shell: |
    export CARGO_HOME=/opt/cargo
    export RUSTUP_HOME=/opt/rustup
    curl https://sh.rustup.rs -sSf |
      sh -s -- --default-toolchain stable --profile default --no-modify-path -y
  args:
    creates: /opt/cargo/bin/rustup

- name: Update bashrc
  ansible.builtin.blockinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    create: true
    block: "{{ lookup('ansible.builtin.file', '{{ role_path }}/files/bashrc_extra.sh') }}"
    marker: "# {mark} $DOTFILES/roles/cargo"
    state: present

- name: Symlink completion
  when: "'fish' in role_names"
  ansible.builtin.shell: |
    rustup completions fish > "{{ role_path }}/../fish/files/fish/completions/rustup.fish"
  args:
    creates: "{{ role_path }}/../fish/files/fish/completions/rustup.fish"

- name: Read vars
  ansible.builtin.include_vars: "{{ ansible_distribution | lower }}.yml"

- name: Install default cargo packages
  community.general.cargo:
    name: "{{ crates }}"
    state: present
  when: crates
