- name: Install updater
  block:
    - name: Install updater
      community.general.pipx:
        name: awscli-update
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Install updater
      ansible.builtin.pip:
        name: awscli-update
        state: present
      when: ansible_distribution == "Archlinux"

- name: Install awscli
  ansible.builtin.shell: |
    awscli-update -q --prefix "$HOME/.local"
  args:
    creates: "{{ ansible_user_dir }}/.local/bin/aws"

- name: Setup update timer
  block:
    - name: Copy service
      ansible.builtin.file:
        src: "{{ role_path }}/files/awscli-update.service"
        dest: "{{ ansible_user_dir }}/.config/systemd/user/awscli-update.service"
        state: link
        force: true
    - name: Copy timer
      ansible.builtin.file:
        src: "{{ role_path }}/files/awscli-update.timer"
        dest: "{{ ansible_user_dir }}/.config/systemd/user/awscli-update.timer"
        state: link
        force: true
    - name: Start timer
      ansible.builtin.service:
        name: awscli-update.timer
        state: started
        scope: user
        enabled: true
