#!/bin/bash

# shamelessly stolen from:
# https://adamsimpson.net/writing/getting-started-with-rofi

source="$(pactl list short sources | grep alsa_input | cut -f2 | rofi -dmenu -p "Change audio input")"
rofi_exit=$?
if [[ $rofi_exit -ne 0 ]]; then
  exit
fi
outputs="$(pactl list source-outputs short | cut -f1)"

for output in $outputs; do
  pactl move-source-output "$output" "$source"
done

pactl set-default-source "$source"
