#!/bin/bash
set -e

# shellcheck source=/home/adg/.bin/clack
source "$(which clack)" --source

api_url="$(_clack_base_url)reminders"

function list {
    curl -s \
        -H "$(_clack_header_auth)" \
        "$api_url.list"
}

function info {
    curl -s \
        -H "$(_clack_header_auth)" \
        --data-urlencode "reminder=$1" \
        "$api_url.info"
}

function complete {
    curl -s \
        -X POST \
        -H "$(_clack_header_auth)" \
        --data-urlencode "reminder=$1" \
        "$api_url.complete"
}

function delete {
    curl -s \
        -X POST \
        -H "$(_clack_header_auth)" \
        --data-urlencode "reminder=$1" \
        "$api_url.delete"
}

function add {
    curl -s \
        -X POST \
        -H "$(_clack_header_auth)" \
        --data-urlencode "text=$1" \
        --data-urlencode "time=$2" \
        "$api_url.add"
}

if [[ $# -lt 1 ]]; then
    list
else
    case $1 in
        add)
            add "$2" "$3"
            ;;
        complete)
            complete "$2"
            ;;
        delete)
            delete "$2"
            ;;
        info)
            info "$2"
            ;;
        list)
            list
            ;;
    esac
fi
