#!/bin/bash
set -e

CLACK_BASE_URL='https://slack.com/api/'
CLACK_TOCKEN_FILE="$HOME/.slack_token"
CLACK_HEADER_AUTH='Authorization: Bearer'

function _clack_base_url {
    echo $CLACK_BASE_URL
}

function _clack_token {
    if [[ -r $CLACK_TOCKEN_FILE && -s $CLACK_TOCKEN_FILE ]]; then
        cat "$CLACK_TOCKEN_FILE"
    else
        echo "Please provide slack token in '$CLACK_TOCKEN_FILE'."
        echo "You can get this token at 'https://api.slack.com/custom-integrations/legacy-tokens'."
        exit 1
    fi
}

function _clack_header_auth {
    echo "$CLACK_HEADER_AUTH $(_clack_token)"
}

if [[ $# -lt 1 ]]; then
    exit 1
elif [[ $1 == "--source" ]]; then
    :
else
    if which "clack-$1" >/dev/null 2>&1; then
        "clack-$1" "${@:2}"
    else
        echo "clack: '$1' is not a clack command. See 'clack --help'."
        exit 1
    fi
fi
