#!/bin/bash
set -e

FILE="/tmp/dnd-$(date "+%F")"

function dnd-start {
    if ! pidof cmus >/dev/null; then
        tmux new-window -t 0 -d cmus
        sleep 1
    fi
    cmus-remote -p
    notify-send -t 5000 dnd "until $(date -d "@$(clack dnd start 60 | jq '.snooze_endtime')")"
}

function dnd-stop {
    cmus-remote -u
    clack dnd stop
    notify-send -t 5000 dnd "stopped"
}

if [[ -f $FILE ]]; then
    dnd-stop
    rm "$FILE"
else
    dnd-start
    touch "$FILE"
fi
