#!/usr/bin/awk -f

BEGIN {
    while ("git branch -vv" | getline)
        if (/: gone]/) {
            if (ARGV[1] ~ "^f")
                system("git branch -d " $1)
            else
                system("git branch -D " $1)
        }
}
