set -x fish_color_autosuggestion 586e75
set -x fish_color_command 268bd2
set -x fish_color_comment 586e75
set -x fish_color_cwd green
set -x fish_color_cwd_root red
set -x fish_color_end 268bd2
set -x fish_color_error cb4b16
set -x fish_color_escape cyan
set -x fish_color_history_current cyan
set -x fish_color_host \x2do\x1ecyan
set -x fish_color_match cyan
set -x fish_color_normal normal
set -x fish_color_operator cyan
set -x fish_color_param b58900
set -x fish_color_quote 859900
set -x fish_color_redirection 6c71c4
set -x fish_color_search_match \x2d\x2dbackground\x3dpurple
set -x fish_color_selection \x2d\x2dbackground\x3dpurple
set -x fish_color_status red
set -x fish_color_user \x2do\x1egreen
set -x fish_color_valid_path \x2d\x2dunderline
set -x fish_key_bindings fish_default_key_bindings
set -x fish_pager_color_completion normal
set -x fish_pager_color_description 555\x1eyellow
set -x fish_pager_color_prefix cyan
set -x fish_pager_color_progress cyan
