packages:
  - base-devel
  - gawk
  - gradle
  - inotify-tools
  - jq
  - maven
  - nmap
  - jre11-openjdk-headless
  - jre11-openjdk-headless
  - shellcheck
  - socat
  - yq

flatpaks:
  - com.getpostman.Postman
  - com.visualstudio.code
  - org.raspberrypi.rpi-imager

crates:
  - cargo-audit
  - cargo-outdated
  - cargo-tarpaulin
  - cargo-update
  - cargo-watch
