- name: Check for OS specific settings
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution | lower }}.yml"
  register: custom_settings

- name: Apply OS specific settings
  ansible.builtin.include_tasks:
    "{{ role_path }}/tasks/{{ ansible_distribution | lower }}.yml"
  when: custom_settings.stat.exists

- name: Add to docker group
  become: true
  ansible.builtin.user:
    name: "{{ user }}"
    groups: "{{ role_name }}"
    append: true
