- name: Ensure base directories exists
  block:
    - name: Ensure .config exists
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/.config"
        state: directory
        mode: "0755"

    - name: Ensure .config/systemd/user exists
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/.config/systemd/user"
        state: directory
        mode: "0755"

    - name: Ensure .local exists
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/.local"
        state: directory
        mode: "0700"

    - name: Ensure .local/share exists
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/.local/share"
        state: directory
        mode: "0700"

    - name: Ensure .local/bin exists
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/.local/bin"
        state: directory
        mode: "0700"
