- name: Update package cache
  become: true
  block:
    - name: Update 'apt' cache
      ansible.builtin.apt:
        update_cache: true
      when: ansible_distribution == "Ubuntu"
      changed_when: false
