#!/bin/bash

# Dependencies: imagemagick, i3lock-color-git, scrot

IMAGE=$(mktemp).png

# get path where the script is located
# its used for the lock icon
pushd "$(dirname "$0")" > /dev/null
SCRIPTPATH=$PWD
popd > /dev/null
 
scrot "$IMAGE"
# pixelate: -scale 10% -scale 1000%
convert "$IMAGE" -scale 10% -scale 1000% \
    "$SCRIPTPATH/lock.png" -gravity center -composite "$IMAGE"
PARAM="--textcolor=00000000 \
    --insidecolor=0000001c \
    --ringcolor=0000003e \
    --linecolor=00000000 \
    --keyhlcolor=ffffff80 \
    --ringvercolor=ffffff00 \
    --insidevercolor=ffffff1c \
    --ringwrongcolor=ffffff55 \
    --insidewrongcolor=ffffff1c"

# try to use a forked version of i3lock with prepared parameters
if i3lock "$PARAM" -i "$IMAGE" > /dev/null 2>&1; then
    # We have failed, lets get back to stock one
    i3lock -i "$IMAGE"
fi

rm "$IMAGE"
