#!/bin/sh

ID=`xinput list | grep TouchPad | sed -n 's/.*\(id=\)\([0-9]*\).*/\2/p'`
if [ -n "$ID" ]; then
    STATE=`xinput list-props $ID | grep 'Device Enabled' | awk '{print $4}'`
    if [ $STATE -eq 1 ]; then
        xinput disable $ID
    else
        xinput enable $ID
    fi
    echo $STATE
fi
