#!/bin/sh

exec xautolock -detectsleep \
    -time 3 -locker "$HOME/.i3/i3lock-img" \
    -corners -+00 \
    -cornerdelay 5 \
    -cornerredelay 10 \
    -notify 5 \
    -notifier "timeout 4 i3-nagbar -t warning -m 'LOCKING screen in 5 seconds'"
